server.port=${PORT:8080}
spring.application.name=helpdesk

# Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# AI Configuration
groq.api.key=${groq.api.key}
groq.api.url=https://api.groq.com/openai/v1/chat/completions

# Secret Key
jwt.secret=${JWT_SECRET}

# SMTP Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${MAIL_PASSWORD}

# Mail Protocol Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB