server.port=${PORT:8080}
spring.application.name=helpdesk

# Database Connection
spring.datasource.url=jdbc:postgresql://ep-crimson-violet-ao1z74ry.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_b0K9onLVICQS
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AI Configuration
gemini.api.key=AQ.Ab8RN6JEjs007lCYveVRWPJdbWqdcaWpgrb6kA1Uu5Sn7Ql7rg
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Secret Key
jwt.secret=4qhq8Ir39bjhV+8h9q873q87gq87gq87gq87gq87gq87gq87gq87gq87gq87gq87gq87g=

